build = "cargo build --release -p 'llms-sdk'"
test = "cargo test --release --all-features -p 'llms-sdk'"
integration = "cargo test --release --all-features --test integration_test -p 'llms-sdk' -- --ignored"
test-no-fs = "cargo test --release --no-default-features -p 'llms-sdk'"
clippy = "cargo clippy --all-features"
clippy-fix = "cargo clippy --all-features --fix --allow-dirty"
format = "cargo fmt --all -- --check"
format-fix = "cargo fmt --all"
