/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * LLM client.
 *
 * Create an instance with `new LLM(retryPolicy?)` and call
 * `respond()` for a one-shot completion or `streamResponse()`
 * for streaming output via a callback.
 */
export declare class Llm {
  /**
   * Create a new LLM client.
   *
   * @param retryPolicy - Optional retry policy. Defaults to 3 retries with
   *   exponential backoff between 500 ms and 3000 ms.
   */
  constructor(retryPolicy?: RetryPolicy | undefined | null)
  /**
   * Send a single request and wait for the full response.
   *
   * @param request - The [`LLMRequest`] to send.
   * @returns A complete [`LLMResponse`] containing the generated message and usage stats.
   */
  respond(request: LlmRequest): Promise<LlmResponse>
  /**
   * Stream a response incrementally through a JavaScript callback.
   *
   * The callback is invoked for every chunk (`LLMStreamingResponse`) as it
   * arrives from the provider. The final chunk is always a `Complete` variant.
   *
   * @param request - The [`LLMRequest`] to send.
   * @param callback - Node-style callback receiving `(err, chunk)`.
   */
  streamResponse(
    request: LlmRequest,
    callback: (err: Error | null, chunk?: LLMStreamingResponse) => void,
  ): Promise<void>
}
export type LLM = Llm

/** Supported LLM API providers. */
export declare const enum ApiType {
  OpenAI = 'openai',
  Anthropic = 'anthropic',
}

/**
 * Create an [`AudioPart`] from a file path or raw bytes.
 *
 * @param input - Either a file path (`string`) or a `Buffer` containing audio data.
 * @returns An `AudioPart` ready to be added to a [`Message`].
 */
export declare function audioPart(input: string | Buffer): AudioPart

/**
 * Audio segment of a message.
 *
 * Created via [`audio_part()`].
 */
export interface AudioPart {
  /** Base64-encoded audio data. */
  data: string
  /** MIME type of the audio (e.g. `audio/mpeg`). */
  mimeType: string
}

/**
 * Create a [`DocumentPart`] from a URL, file path, or raw bytes.
 *
 * @param input - Either a URL/path (`string`) or a `Buffer` containing PDF data.
 * @returns A `DocumentPart` ready to be added to a [`Message`].
 */
export declare function documentPart(input: string | Buffer): DocumentPart

/**
 * Document segment of a message (PDF or plain text).
 *
 * Created via [`document_part()`].
 */
export interface DocumentPart {
  /** Raw document data (base64-encoded) or a URL. */
  data: string
  /** MIME type of the document, when known. */
  mimeType?: string
  /** Whether `data` is base64-encoded (`true`) or a URL (`false`). */
  isBase64: boolean
}

/**
 * Create an [`ImagePart`] from a URL, file path, or raw bytes.
 *
 * @param input - Either a URL/path (`string`) or a `Buffer` containing image data.
 * @returns An `ImagePart` ready to be added to a [`Message`].
 */
export declare function imagePart(input: string | Buffer): ImagePart

/**
 * Image segment of a message.
 *
 * Created via [`image_part()`].
 */
export interface ImagePart {
  /** Raw image data (base64-encoded) or a URL. */
  data: string
  /** MIME type of the image, when known. */
  mimeType?: string
  /** Whether `data` is base64-encoded (`true`) or a URL (`false`). */
  isBase64: boolean
}

/** Request payload sent to the LLM. */
export interface LlmRequest {
  /** Target API provider. */
  apiType: ApiType
  /** Custom base URL for the API. When `None`, the provider's default is used. */
  baseUrl?: string
  /** API key used to authenticate the request. */
  apiKey: string
  /** Model identifier to use for the request. */
  model: string
  /** Conversation history sent to the model. */
  messages: Array<Message>
  /** Maximum number of tokens the model is allowed to generate. */
  maxOutputTokens?: number
  /** Sampling temperature (0 = deterministic, higher = more random). */
  temperature?: number
  /** Nucleus sampling parameter (0–1). */
  topP?: number
  /** Level of reasoning effort requested from the model. */
  reasoningEffort?: ReasoningEffort
  /** Prompt cache time-to-live hint (provider-specific format). */
  promptCacheTtl?: string
  /** Whether to request a streamed response. */
  stream: boolean
  /** Optional JSON schema for structured outputs. */
  outputFormat?: OutputFormat
  /** Tool definitions made available to the model. */
  tools?: Array<Tool>
  /** Controls whether the model may call tools. */
  toolChoice?: ToolChoice
  /** Whether the model may call multiple tools in parallel. */
  parallelToolCalls: boolean
}

/** A complete, non-streaming response from the LLM. */
export interface LlmResponse {
  /** Provider-generated response identifier. */
  id: string
  /** Unix timestamp of the response, when provided by the API. */
  createdAt?: number
  /** The generated message. */
  message: Message
  /** Token usage reported for the request. */
  usage: LlmUsage
}

/** Final aggregated payload emitted at the end of a streaming response. */
export interface LlmStreamingComplete {
  /** Provider-generated response identifier. */
  id: string
  /** Unix timestamp of the response, when provided by the API. */
  createdAt?: number
  /** The final assembled message. */
  message: Message
  /** All text deltas that make up the response. */
  deltas: Array<LlmStreamingDelta>
  /** All reasoning deltas, if the model produced any. */
  thinkingDeltas?: Array<LlmThinkingDelta>
  /** Token usage reported for the request, if provided. */
  usage?: LlmUsage
  /** Complete tool calls parsed from the stream. */
  toolCalls?: Array<ToolCallPart>
}

/** A partial text delta in a streaming response. */
export interface LlmStreamingDelta {
  /** Identifier of the response this delta belongs to. */
  responseId: string
  /** Unix timestamp of the response, when provided by the API. */
  createdAt?: number
  /** Chunk of generated text, if any. */
  delta?: string
  /** Whether this delta signals the end of the stream. */
  stop: boolean
}

/** A single item emitted by a streaming LLM response. */
export type LLMStreamingResponse =
  | { type: 'Delta'; field0: LlmStreamingDelta }
  | { type: 'ToolDelta'; field0: LlmToolDelta }
  | { type: 'ThinkingDelta'; field0: LlmThinkingDelta }
  | { type: 'Complete'; field0: LlmStreamingComplete }

/** A partial reasoning/thinking delta in a streaming response. */
export interface LlmThinkingDelta {
  /** Identifier of the response this delta belongs to. */
  responseId: string
  /** Unix timestamp of the response, when provided by the API. */
  createdAt?: number
  /** Chunk of reasoning text, if any. */
  delta?: string
}

/** A partial tool call argument delta in a streaming response. */
export interface LlmToolDelta {
  /** Identifier for the in-progress tool call. */
  toolCallId: string
  /** Name of the tool being called. */
  name: string
  /** Partial JSON arguments accumulated so far. */
  partialArguments: string
}

/** Token usage reported by the LLM API. */
export interface LlmUsage {
  /** Tokens consumed by the prompt. */
  inputTokens: number
  /** Tokens generated in the response. */
  outputTokens: number
  /** Tokens read from a provider cache, when applicable. */
  cacheReadTokens?: number
  /** Tokens written to a provider cache, when applicable. */
  cacheWriteTokens?: number
  /** Any additional tokens counted by the provider. */
  otherTokens?: number
}

/** A single turn in the conversation. */
export interface Message {
  /** Who produced this message (user, assistant, system, or tool). */
  role: MessageRole
  /** Ordered list of content parts that make up the message. */
  content: Array<MessagePart>
}

/** A single item inside a [`Message`]'s content array. */
export type MessagePart =
  | { type: 'Text'; field0: TextPart }
  | { type: 'Image'; field0: ImagePart }
  | { type: 'Document'; field0: DocumentPart }
  | { type: 'Audio'; field0: AudioPart }
  | { type: 'ToolCall'; field0: ToolCallPart }
  | { type: 'ToolResult'; field0: ToolResultPart }
  | { type: 'Thinking'; field0: ThinkingPart }

/** Role of a message in the conversation. */
export declare const enum MessageRole {
  User = 'user',
  Assistant = 'assistant',
  System = 'system',
  Tool = 'tool',
}

/** Structured-output format enforced on the model response. */
export interface OutputFormat {
  /** Name of the output format. */
  name: string
  /** Human-readable description. */
  description: string
  /** JSON schema the model output must conform to. */
  schema: any
}

/** Amount of reasoning effort the model should expend. */
export declare const enum ReasoningEffort {
  None = 'none',
  Minimal = 'minimal',
  Low = 'low',
  Medium = 'medium',
  High = 'high',
  Xhigh = 'xhigh',
  Maximum = 'maximum',
}

/** Retry configuration used when constructing an [`LLM`]. */
export interface RetryPolicy {
  /** Maximum number of retries before giving up. */
  maxRetries: number
  /** Minimum wait time between retries, in milliseconds. */
  minRetryInterval: number
  /** Maximum wait time between retries, in milliseconds. */
  maxRetryInterval: number
  /** Exponential backoff base. */
  base: number
}

/** Plain-text segment of a message. */
export interface TextPart {
  text: string
}

/** A reasoning/thinking block produced by the model. */
export interface ThinkingPart {
  /** The model's internal reasoning text. */
  thinking: string
  /** Cryptographic signature verifying the reasoning, when provided. */
  signature?: string
}

/** A tool definition made available to the model. */
export interface Tool {
  /** Name of the tool. */
  name: string
  /** Human-readable description of what the tool does. */
  description: string
  /** JSON schema representing the tool parameters. */
  parameters: any
}

/** A tool call issued by the model. */
export interface ToolCallPart {
  /** Unique identifier for this tool call. */
  id: string
  /** Name of the tool being invoked. */
  name: string
  /** JSON-encoded arguments for the tool call. */
  arguments: string
}

/** Controls whether the model is allowed to call tools. */
export declare const enum ToolChoice {
  None = 'none',
  Auto = 'auto',
  Required = 'required',
}

/** Result returned to the model after executing a tool call. */
export interface ToolResultPart {
  /** Identifier of the original tool call this result belongs to. */
  toolCallId: string
  /** JSON-encoded result payload. */
  result: string
}
